apiVersion: v1
kind: Service
metadata:
  name: {{ include "hanzo-mpc.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "hanzo-mpc.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: api
      protocol: TCP
      name: api
    - port: 6000
      targetPort: mpc
      protocol: TCP
      name: mpc
  selector:
    app.kubernetes.io/name: {{ include "hanzo-mpc.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
