apiVersion: v1
kind: Service
metadata:
  name: {{ include "hanzo-net.controller.fullname" . }}
  labels:
    {{- include "hanzo-net.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  type: {{ .Values.controller.service.type }}
  ports:
    - port: {{ .Values.controller.service.port }}
      targetPort: edge
      protocol: TCP
      name: edge
    - port: {{ .Values.controller.service.mgmtPort }}
      targetPort: mgmt
      protocol: TCP
      name: mgmt
  selector:
    {{- include "hanzo-net.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller
