apiVersion: v1
kind: Service
metadata:
  name: {{ include "hanzo-net.router.fullname" . }}
  labels:
    {{- include "hanzo-net.labels" . | nindent 4 }}
    app.kubernetes.io/component: router
spec:
  type: {{ .Values.router.service.type }}
  ports:
    - port: {{ .Values.router.service.port }}
      targetPort: edge
      protocol: TCP
      name: edge
    - port: {{ .Values.router.service.transportPort }}
      targetPort: transport
      protocol: TCP
      name: transport
  selector:
    {{- include "hanzo-net.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: router
